/*
walt.id Signatory API

The walt.id public API documentation

API version: 1.1-SNAPSHOT
Contact: office@walt.id
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// IssueCredentialRequest struct for IssueCredentialRequest
type IssueCredentialRequest struct {
	TemplateId string `json:"templateId"`
	Config ProofConfig `json:"config"`
}

// NewIssueCredentialRequest instantiates a new IssueCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssueCredentialRequest(templateId string, config ProofConfig) *IssueCredentialRequest {
	this := IssueCredentialRequest{}
	this.TemplateId = templateId
	this.Config = config
	return &this
}

// NewIssueCredentialRequestWithDefaults instantiates a new IssueCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssueCredentialRequestWithDefaults() *IssueCredentialRequest {
	this := IssueCredentialRequest{}
	return &this
}

// GetTemplateId returns the TemplateId field value
func (o *IssueCredentialRequest) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *IssueCredentialRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *IssueCredentialRequest) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetConfig returns the Config field value
func (o *IssueCredentialRequest) GetConfig() ProofConfig {
	if o == nil {
		var ret ProofConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *IssueCredentialRequest) GetConfigOk() (*ProofConfig, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *IssueCredentialRequest) SetConfig(v ProofConfig) {
	o.Config = v
}

func (o IssueCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["templateId"] = o.TemplateId
	}
	if true {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableIssueCredentialRequest struct {
	value *IssueCredentialRequest
	isSet bool
}

func (v NullableIssueCredentialRequest) Get() *IssueCredentialRequest {
	return v.value
}

func (v *NullableIssueCredentialRequest) Set(val *IssueCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIssueCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIssueCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssueCredentialRequest(val *IssueCredentialRequest) *NullableIssueCredentialRequest {
	return &NullableIssueCredentialRequest{value: val, isSet: true}
}

func (v NullableIssueCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssueCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


