/**
 * walt.id Custodian API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltIdCustodianApi);
  }
}(this, function(expect, WaltIdCustodianApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltIdCustodianApi.CredentialsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CredentialsApi', function() {
    describe('deleteCredential', function() {
      it('should call deleteCredential successfully', function(done) {
        //uncomment below and update the code to test deleteCredential
        //instance.deleteCredential(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCredential', function() {
      it('should call getCredential successfully', function(done) {
        //uncomment below and update the code to test getCredential
        //instance.getCredential(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCredentialIds', function() {
      it('should call listCredentialIds successfully', function(done) {
        //uncomment below and update the code to test listCredentialIds
        //instance.listCredentialIds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCredentials', function() {
      it('should call listCredentials successfully', function(done) {
        //uncomment below and update the code to test listCredentials
        //instance.listCredentials(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeCredential', function() {
      it('should call storeCredential successfully', function(done) {
        //uncomment below and update the code to test storeCredential
        //instance.storeCredential(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
