/**
 * walt.id Signatory API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltIdSignatoryApi);
  }
}(this, function(expect, WaltIdSignatoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltIdSignatoryApi.IssueCredentialRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IssueCredentialRequest', function() {
    it('should create an instance of IssueCredentialRequest', function() {
      // uncomment below and update the code to test IssueCredentialRequest
      //var instance = new WaltIdSignatoryApi.IssueCredentialRequest();
      //expect(instance).to.be.a(WaltIdSignatoryApi.IssueCredentialRequest);
    });

    it('should have the property templateId (base name: "templateId")', function() {
      // uncomment below and update the code to test the property templateId
      //var instance = new WaltIdSignatoryApi.IssueCredentialRequest();
      //expect(instance).to.be();
    });

    it('should have the property config (base name: "config")', function() {
      // uncomment below and update the code to test the property config
      //var instance = new WaltIdSignatoryApi.IssueCredentialRequest();
      //expect(instance).to.be();
    });

  });

}));
