/**
 * walt.id Signatory API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltIdSignatoryApi);
  }
}(this, function(expect, WaltIdSignatoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltIdSignatoryApi.ProofConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProofConfig', function() {
    it('should create an instance of ProofConfig', function() {
      // uncomment below and update the code to test ProofConfig
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be.a(WaltIdSignatoryApi.ProofConfig);
    });

    it('should have the property issuerDid (base name: "issuerDid")', function() {
      // uncomment below and update the code to test the property issuerDid
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property subjectDid (base name: "subjectDid")', function() {
      // uncomment below and update the code to test the property subjectDid
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property verifierDid (base name: "verifierDid")', function() {
      // uncomment below and update the code to test the property verifierDid
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property issuerVerificationMethod (base name: "issuerVerificationMethod")', function() {
      // uncomment below and update the code to test the property issuerVerificationMethod
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property proofType (base name: "proofType")', function() {
      // uncomment below and update the code to test the property proofType
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property nonce (base name: "nonce")', function() {
      // uncomment below and update the code to test the property nonce
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property proofPurpose (base name: "proofPurpose")', function() {
      // uncomment below and update the code to test the property proofPurpose
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property credentialId (base name: "credentialId")', function() {
      // uncomment below and update the code to test the property credentialId
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property issueDate (base name: "issueDate")', function() {
      // uncomment below and update the code to test the property issueDate
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property validDate (base name: "validDate")', function() {
      // uncomment below and update the code to test the property validDate
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property expirationDate (base name: "expirationDate")', function() {
      // uncomment below and update the code to test the property expirationDate
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

    it('should have the property dataProviderIdentifier (base name: "dataProviderIdentifier")', function() {
      // uncomment below and update the code to test the property dataProviderIdentifier
      //var instance = new WaltIdSignatoryApi.ProofConfig();
      //expect(instance).to.be();
    });

  });

}));
