/**
 * walt.id Core API
 *
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param keyAlias 
 * @param format 
 * @param exportPrivate 
 */

data class ExportKeyRequest (

    @Json(name = "keyAlias")
    val keyAlias: kotlin.String,

    @Json(name = "format")
    val format: ExportKeyRequest.Format,

    @Json(name = "exportPrivate")
    val exportPrivate: kotlin.Boolean

) {

    /**
     * 
     *
     * Values: jWK,pEM
     */
    enum class Format(val value: kotlin.String) {
        @Json(name = "JWK") jWK("JWK"),
        @Json(name = "PEM") pEM("PEM");
    }
}

