/*
walt.id Core API

The walt.id public API documentation

API version: 1.1-SNAPSHOT
Contact: office@walt.id
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KeyId struct for KeyId
type KeyId struct {
	Id string `json:"id"`
}

// NewKeyId instantiates a new KeyId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyId(id string) *KeyId {
	this := KeyId{}
	this.Id = id
	return &this
}

// NewKeyIdWithDefaults instantiates a new KeyId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyIdWithDefaults() *KeyId {
	this := KeyId{}
	return &this
}

// GetId returns the Id field value
func (o *KeyId) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KeyId) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KeyId) SetId(v string) {
	o.Id = v
}

func (o KeyId) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableKeyId struct {
	value *KeyId
	isSet bool
}

func (v NullableKeyId) Get() *KeyId {
	return v.value
}

func (v *NullableKeyId) Set(val *KeyId) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyId) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyId(val *KeyId) *NullableKeyId {
	return &NullableKeyId{value: val, isSet: true}
}

func (v NullableKeyId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


