/**
 * walt.id Custodian API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VerifiableCredential from './VerifiableCredential';

/**
 * The StoreCredentialRequest model module.
 * @module model/StoreCredentialRequest
 * @version 1.1-SNAPSHOT
 */
class StoreCredentialRequest {
    /**
     * Constructs a new <code>StoreCredentialRequest</code>.
     * @alias module:model/StoreCredentialRequest
     * @param alias {String} 
     * @param vc {module:model/VerifiableCredential} 
     */
    constructor(alias, vc) { 
        
        StoreCredentialRequest.initialize(this, alias, vc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, alias, vc) { 
        obj['alias'] = alias;
        obj['vc'] = vc;
    }

    /**
     * Constructs a <code>StoreCredentialRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreCredentialRequest} obj Optional instance to populate.
     * @return {module:model/StoreCredentialRequest} The populated <code>StoreCredentialRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreCredentialRequest();

            if (data.hasOwnProperty('alias')) {
                obj['alias'] = ApiClient.convertToType(data['alias'], 'String');
            }
            if (data.hasOwnProperty('vc')) {
                obj['vc'] = VerifiableCredential.constructFromObject(data['vc']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} alias
 */
StoreCredentialRequest.prototype['alias'] = undefined;

/**
 * @member {module:model/VerifiableCredential} vc
 */
StoreCredentialRequest.prototype['vc'] = undefined;






export default StoreCredentialRequest;

