/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltIdCoreApi);
  }
}(this, function(expect, WaltIdCoreApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltIdCoreApi.KeyManagementApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KeyManagementApi', function() {
    describe('deleteKey', function() {
      it('should call deleteKey successfully', function(done) {
        //uncomment below and update the code to test deleteKey
        //instance.deleteKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('exportKey', function() {
      it('should call exportKey successfully', function(done) {
        //uncomment below and update the code to test exportKey
        //instance.exportKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('genKey', function() {
      it('should call genKey successfully', function(done) {
        //uncomment below and update the code to test genKey
        //instance.genKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1KeyWithId', function() {
      it('should call getV1KeyWithId successfully', function(done) {
        //uncomment below and update the code to test getV1KeyWithId
        //instance.getV1KeyWithId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('importKey', function() {
      it('should call importKey successfully', function(done) {
        //uncomment below and update the code to test importKey
        //instance.importKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listKeys', function() {
      it('should call listKeys successfully', function(done) {
        //uncomment below and update the code to test listKeys
        //instance.listKeys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
