/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltIdCoreApi);
  }
}(this, function(expect, WaltIdCoreApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltIdCoreApi.VerifiableCredentialsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VerifiableCredentialsApi', function() {
    describe('createVc', function() {
      it('should call createVc successfully', function(done) {
        //uncomment below and update the code to test createVc
        //instance.createVc(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVc', function() {
      it('should call deleteVc successfully', function(done) {
        //uncomment below and update the code to test deleteVc
        //instance.deleteVc(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('importVc', function() {
      it('should call importVc successfully', function(done) {
        //uncomment below and update the code to test importVc
        //instance.importVc(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listVcs', function() {
      it('should call listVcs successfully', function(done) {
        //uncomment below and update the code to test listVcs
        //instance.listVcs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('loadVc', function() {
      it('should call loadVc successfully', function(done) {
        //uncomment below and update the code to test loadVc
        //instance.loadVc(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyVc', function() {
      it('should call verifyVc successfully', function(done) {
        //uncomment below and update the code to test verifyVc
        //instance.verifyVc(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
