/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaltIdCoreApi);
  }
}(this, function(expect, WaltIdCoreApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaltIdCoreApi.PresentVcRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PresentVcRequest', function() {
    it('should create an instance of PresentVcRequest', function() {
      // uncomment below and update the code to test PresentVcRequest
      //var instance = new WaltIdCoreApi.PresentVcRequest();
      //expect(instance).to.be.a(WaltIdCoreApi.PresentVcRequest);
    });

    it('should have the property vc (base name: "vc")', function() {
      // uncomment below and update the code to test the property vc
      //var instance = new WaltIdCoreApi.PresentVcRequest();
      //expect(instance).to.be();
    });

    it('should have the property holderDid (base name: "holderDid")', function() {
      // uncomment below and update the code to test the property holderDid
      //var instance = new WaltIdCoreApi.PresentVcRequest();
      //expect(instance).to.be();
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instance = new WaltIdCoreApi.PresentVcRequest();
      //expect(instance).to.be();
    });

    it('should have the property challenge (base name: "challenge")', function() {
      // uncomment below and update the code to test the property challenge
      //var instance = new WaltIdCoreApi.PresentVcRequest();
      //expect(instance).to.be();
    });

  });

}));
