/**
 * walt.id Custodian API
 * The walt.id public API documentation
 *
 * OpenAPI spec version: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GenerateKeyRequest {
    'keyAlgorithm': GenerateKeyRequestKeyAlgorithmEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyAlgorithm",
            "baseName": "keyAlgorithm",
            "type": "GenerateKeyRequestKeyAlgorithmEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerateKeyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type GenerateKeyRequestKeyAlgorithmEnum = "EdDSA_Ed25519" | "ECDSA_Secp256k1" ;

