/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateVcRequest model module.
 * @module model/CreateVcRequest
 * @version 1.1-SNAPSHOT
 */
class CreateVcRequest {
    /**
     * Constructs a new <code>CreateVcRequest</code>.
     * @alias module:model/CreateVcRequest
     * @param issuerDid {String} 
     */
    constructor(issuerDid) { 
        
        CreateVcRequest.initialize(this, issuerDid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, issuerDid) { 
        obj['issuerDid'] = issuerDid;
    }

    /**
     * Constructs a <code>CreateVcRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateVcRequest} obj Optional instance to populate.
     * @return {module:model/CreateVcRequest} The populated <code>CreateVcRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateVcRequest();

            if (data.hasOwnProperty('issuerDid')) {
                obj['issuerDid'] = ApiClient.convertToType(data['issuerDid'], 'String');
            }
            if (data.hasOwnProperty('subjectDid')) {
                obj['subjectDid'] = ApiClient.convertToType(data['subjectDid'], 'String');
            }
            if (data.hasOwnProperty('credentialOffer')) {
                obj['credentialOffer'] = ApiClient.convertToType(data['credentialOffer'], 'String');
            }
            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} issuerDid
 */
CreateVcRequest.prototype['issuerDid'] = undefined;

/**
 * @member {String} subjectDid
 */
CreateVcRequest.prototype['subjectDid'] = undefined;

/**
 * @member {String} credentialOffer
 */
CreateVcRequest.prototype['credentialOffer'] = undefined;

/**
 * @member {String} templateId
 */
CreateVcRequest.prototype['templateId'] = undefined;

/**
 * @member {String} domain
 */
CreateVcRequest.prototype['domain'] = undefined;

/**
 * @member {String} nonce
 */
CreateVcRequest.prototype['nonce'] = undefined;






export default CreateVcRequest;

