/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KeyId model module.
 * @module model/KeyId
 * @version 1.1-SNAPSHOT
 */
class KeyId {
    /**
     * Constructs a new <code>KeyId</code>.
     * @alias module:model/KeyId
     * @param id {String} 
     */
    constructor(id) { 
        
        KeyId.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>KeyId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KeyId} obj Optional instance to populate.
     * @return {module:model/KeyId} The populated <code>KeyId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KeyId();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
KeyId.prototype['id'] = undefined;






export default KeyId;

