/**
 * walt.id Signatory API
 *
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProofConfig

import com.squareup.moshi.Json

/**
 * 
 *
 * @param templateId 
 * @param config 
 */

data class IssueCredentialRequest (

    @Json(name = "templateId")
    val templateId: kotlin.String,

    @Json(name = "config")
    val config: ProofConfig

)

