/**
 * walt.id Auditor API
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VerificationResult model module.
 * @module model/VerificationResult
 * @version 1.1-SNAPSHOT
 */
class VerificationResult {
    /**
     * Constructs a new <code>VerificationResult</code>.
     * @alias module:model/VerificationResult
     * @param overallStatus {Boolean} 
     * @param policyResults {Object.<String, Boolean>} 
     */
    constructor(overallStatus, policyResults) { 
        
        VerificationResult.initialize(this, overallStatus, policyResults);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, overallStatus, policyResults) { 
        obj['overallStatus'] = overallStatus;
        obj['policyResults'] = policyResults;
    }

    /**
     * Constructs a <code>VerificationResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VerificationResult} obj Optional instance to populate.
     * @return {module:model/VerificationResult} The populated <code>VerificationResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerificationResult();

            if (data.hasOwnProperty('overallStatus')) {
                obj['overallStatus'] = ApiClient.convertToType(data['overallStatus'], 'Boolean');
            }
            if (data.hasOwnProperty('policyResults')) {
                obj['policyResults'] = ApiClient.convertToType(data['policyResults'], {'String': 'Boolean'});
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} overallStatus
 */
VerificationResult.prototype['overallStatus'] = undefined;

/**
 * @member {Object.<String, Boolean>} policyResults
 */
VerificationResult.prototype['policyResults'] = undefined;






export default VerificationResult;

