/**
 * walt.id Custodian API
 *
 * The walt.id public API documentation
 *
 * The version of the OpenAPI document: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param json 
 * @param jwt 
 * @param id 
 */

data class VerifiableCredential (

    @Json(name = "type")
    val type: kotlin.collections.List<kotlin.String>,

    @Json(name = "json")
    val json: kotlin.String? = null,

    @Json(name = "jwt")
    val jwt: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

)

