/**
 * walt.id Signatory API
 * The walt.id public API documentation
 *
 * OpenAPI spec version: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProofConfig {
    'issuerDid': string;
    'subjectDid'?: string;
    'verifierDid'?: string;
    'issuerVerificationMethod'?: string;
    'proofType': ProofConfigProofTypeEnum;
    'domain'?: string;
    'nonce'?: string;
    'proofPurpose'?: string;
    'credentialId'?: string;
    'issueDate'?: Date;
    'validDate'?: Date;
    'expirationDate'?: Date;
    'dataProviderIdentifier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "issuerDid",
            "baseName": "issuerDid",
            "type": "string",
            "format": ""
        },
        {
            "name": "subjectDid",
            "baseName": "subjectDid",
            "type": "string",
            "format": ""
        },
        {
            "name": "verifierDid",
            "baseName": "verifierDid",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuerVerificationMethod",
            "baseName": "issuerVerificationMethod",
            "type": "string",
            "format": ""
        },
        {
            "name": "proofType",
            "baseName": "proofType",
            "type": "ProofConfigProofTypeEnum",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string",
            "format": ""
        },
        {
            "name": "proofPurpose",
            "baseName": "proofPurpose",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentialId",
            "baseName": "credentialId",
            "type": "string",
            "format": ""
        },
        {
            "name": "issueDate",
            "baseName": "issueDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "validDate",
            "baseName": "validDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dataProviderIdentifier",
            "baseName": "dataProviderIdentifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProofConfig.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ProofConfigProofTypeEnum = "JWT" | "LD_PROOF" ;

