/**
 * walt.id Auditor API
 * The walt.id public API documentation
 *
 * OpenAPI spec version: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VerificationResult {
    'overallStatus': boolean;
    'policyResults': { [key: string]: boolean; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "overallStatus",
            "baseName": "overallStatus",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "policyResults",
            "baseName": "policyResults",
            "type": "{ [key: string]: boolean; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VerificationResult.attributeTypeMap;
    }

    public constructor() {
    }
}

