/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * OpenAPI spec version: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateDidRequest {
    'method': CreateDidRequestMethodEnum;
    'keyAlias'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "CreateDidRequestMethodEnum",
            "format": ""
        },
        {
            "name": "keyAlias",
            "baseName": "keyAlias",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDidRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateDidRequestMethodEnum = "key" | "web" | "ebsi" ;

