/**
 * walt.id Core API
 * The walt.id public API documentation
 *
 * OpenAPI spec version: 1.1-SNAPSHOT
 * Contact: office@walt.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExportKeyRequest {
    'keyAlias': string;
    'format': ExportKeyRequestFormatEnum;
    'exportPrivate': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyAlias",
            "baseName": "keyAlias",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "ExportKeyRequestFormatEnum",
            "format": ""
        },
        {
            "name": "exportPrivate",
            "baseName": "exportPrivate",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExportKeyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ExportKeyRequestFormatEnum = "JWK" | "PEM" ;

