/*
walt.id ESSIF API

The walt.id public API documentation

API version: 1.1-SNAPSHOT
Contact: office@walt.id
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EbsiOnboardRequest struct for EbsiOnboardRequest
type EbsiOnboardRequest struct {
	BearerToken string `json:"bearerToken"`
	Did string `json:"did"`
}

// NewEbsiOnboardRequest instantiates a new EbsiOnboardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEbsiOnboardRequest(bearerToken string, did string) *EbsiOnboardRequest {
	this := EbsiOnboardRequest{}
	this.BearerToken = bearerToken
	this.Did = did
	return &this
}

// NewEbsiOnboardRequestWithDefaults instantiates a new EbsiOnboardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEbsiOnboardRequestWithDefaults() *EbsiOnboardRequest {
	this := EbsiOnboardRequest{}
	return &this
}

// GetBearerToken returns the BearerToken field value
func (o *EbsiOnboardRequest) GetBearerToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value
// and a boolean to check if the value has been set.
func (o *EbsiOnboardRequest) GetBearerTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BearerToken, true
}

// SetBearerToken sets field value
func (o *EbsiOnboardRequest) SetBearerToken(v string) {
	o.BearerToken = v
}

// GetDid returns the Did field value
func (o *EbsiOnboardRequest) GetDid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Did
}

// GetDidOk returns a tuple with the Did field value
// and a boolean to check if the value has been set.
func (o *EbsiOnboardRequest) GetDidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Did, true
}

// SetDid sets field value
func (o *EbsiOnboardRequest) SetDid(v string) {
	o.Did = v
}

func (o EbsiOnboardRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bearerToken"] = o.BearerToken
	}
	if true {
		toSerialize["did"] = o.Did
	}
	return json.Marshal(toSerialize)
}

type NullableEbsiOnboardRequest struct {
	value *EbsiOnboardRequest
	isSet bool
}

func (v NullableEbsiOnboardRequest) Get() *EbsiOnboardRequest {
	return v.value
}

func (v *NullableEbsiOnboardRequest) Set(val *EbsiOnboardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEbsiOnboardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEbsiOnboardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEbsiOnboardRequest(val *EbsiOnboardRequest) *NullableEbsiOnboardRequest {
	return &NullableEbsiOnboardRequest{value: val, isSet: true}
}

func (v NullableEbsiOnboardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEbsiOnboardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


